server:
    port: 8092
    
    
spring:
    application:
        name: mpi-service
    datasource:
        platform: postgres
        url: jdbc:postgresql://ec2-34-232-191-133.compute-1.amazonaws.com:5432/d8epsk058u0urm?createDatabaseIfNotExist=true
        username: ejyhcfeekrmayh
        password: 78198d33c63aca031a7859c10a5b005b2fdec0a6f61d0cea6b56ec97833520fc
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
    zipkin:
        base-url: http://127.0.0.1:9411/
            
            
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost

  
