server:
    port: 8092
    
    
spring:
    application:
        name: mpi-service
    datasource:
        platform: postgres
        url: jdbc:postgres://ec2-34-202-54-225.compute-1.amazonaws.com:5432/d4td03se5dd45g?createDatabaseIfNotExist=true        
        username: aflukyyvruzmqv
        password: cdcf873aca9334130a5fc0121ab7be861126889fc6f8110ccd9fbb0e201e552c
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
            
            
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: https://eurekaserverformpi.herokuapp.com/
    instance:
        hostname: https://eurekaserverformpi.herokuapp.com/

  
